import type { ImageSourcePropType } from "react-native";

export const brandIdentity = {
  name: "Intentive",
  initialsFallback: "I",
  mark: "Intentive abstract mark",
} as const;

/**
 * Runtime brand imagery. `brand-head.png` is a first-class app asset, deliberately
 * kept separate from the identical layer inside `assets/Intentive.icon` — that
 * bundle's `Assets/` layout is generated by Icon Composer and re-exporting the
 * app icon may rename or restructure its layers.
 */
export const brandAssets = {
  head: require("../../assets/brand-head.png") as ImageSourcePropType,
} as const;
