version: 2
updates:
  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      pnpm-development:
        dependency-type: development
      pnpm-production:
        dependency-type: production

  - package-ecosystem: cargo
    directory: /apps/desktop/src-tauri
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
